DSR:
  # 若使用此yaml檔案，則需要將 DSR_body.urdf.xacro 的轉向 transmission 作更改，須改回 EffortJointInterface。
  joint_back_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_back_wheel
    pid: {p: 1000.0, i: 0.01, d: 100.0}

  joint_front_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_front_wheel
    pid: {p: 1000.0, i: 0.01, d: 100.0}

  joint_back_motor_wheel_controller:
    type: effort_controllers/JointPositionController
    joint: joint_back_motor
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_front_motor_wheel_controller:
    type: effort_controllers/JointPositionController
    joint: joint_front_motor
    pid: {p: 100.0, i: 0.01, d: 10.0}
  
  joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 100.0
